# general settings
name: train_hat_durlar
model_type: HATModel
scale: 2
num_gpu: auto
manual_seed: 0

# tile: # use the tile mode for limited GPU memory when testing.
#   tile_size: 64 # the higher, the more utilized GPU memory and the less performance change against the full image. must be an integer multiple of the window size.
#   tile_pad: 16 # overlapping between adjacency patches.must be an integer multiple of the window size.

# dataset and data loader settings
datasets:
  test_1:
    name: durlar
    type: PairedRangeMapDataset
    data_folder: /cluster/work/riner/users/biyang/dataset/depth_intensity_new/val/depth/all/
    io_backend:
      type: disk
    # gt_size: 128
    res: "128_2048"
    downsample_factor: 4
    # maximum_range: 80


    # data loader
    use_shuffle: false
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~


# network structures
network_g:
  type: HAT
  upscale: 2
  in_chans: 1
  img_size: 64
  # img_size: 48
  window_size: 4
  # window_size: 4
  compress_ratio: 24
  squeeze_factor: 24
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  # embed_dim: 144
  embed_dim: 96
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: /cluster/home/biyang/ma/sota_reproduce/HAT/experiments/train_hat_carla/models/net_g_367425.pth
  output_path: /cluster/work/riner/users/biyang/experiment/durlar/hat/
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name