dataset:
  name: Durlar
  type: range_samples_from_durlar
  args:
    directory: /cluster/work/riner/users/biyang/iln/samples/
    high_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_large/val/depth/all/
    low_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_large_low_res/val/depth/all/
    # res_in: '16_1024'
    # res_out: '128_2048'
    # num_of_samples: 65536

model:
  name: iln
  output: /cluster/work/riner/users/biyang/experiment/iln
  args:
    d: 4
    h: 8

logger:
  wandb_disabled: False
  project_name: "experiment_upsampling_pt4"
  # project_name: 'implicit_lidar_network'
  entity: "biyang"
  run_name: "eval:iln_4d_50epochs"
  save_pcd: True
