dataset:
  name: Carla
  type: range_samples_from_image
  args:
    directory: /cluster/work/riner/users/biyang/dataset/Carla/
    scene_ids:
      - Town01
      - Town02
      - Town03
      - Town04
      - Town05
      - Town06
    res_in: '16_1024'
    res_out: '256_4096'
    num_of_samples: 16384
    memory_fetch: false

model:
  name: iln
  output: /cluster/work/riner/users/biyang/experiment/x64_upsampling/iln/
  args:
    d: 1
    h: 8

logger:
  wandb_disabled: False
  project_name: "carla_evaluation"
  # project_name: 'implicit_lidar_network'
  entity: "biyang"
  run_name: "iln_16x1024_256x4096"
  save_pcd: True
