dataset:
  name: Durlar
  type: range_samples_from_durlar
  args:
    directory: /cluster/work/riner/users/biyang/iln/samples/
    high_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_new/val/depth/all/
    low_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_new/val/depth/all/
    # res_in: '16_1024'
    # res_out: '128_2048'
    # num_of_samples: 65536

model:
  name: iln
  output: /cluster/work/riner/users/biyang/experiment/durlar/iln_d1/
  args:
    d: 1
    h: 8

logger:
  wandb_disabled: False
  project_name: "durlar_evaluation"
  entity: "biyang"
  run_name: "iln:evaluation_within30m"
  save_pcd: False
  keep_close_scan: True
