dataset:
  name: Durlar
  type: range_samples_from_durlar
  args:
    directory: /cluster/work/riner/users/biyang/iln/samples/
    high_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_large/train/depth/all/
    low_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_large_low_res/train/depth/all/
    # res_in: '16_1024'
    # res_out: '128_2048'
    num_of_samples: 65536

model:
  name: iln
  output: /cluster/work/riner/users/biyang/experiment/iln_d4
  args:
    d: 4
    h: 8

logger:
  wandb_disabled: False
  # evaluation = False
  # save_pcd = False
  # project_name = "lidar_sr_network"
  project_name: 'experiment_upsampling_pt4'
  entity: "biyang"
  run_name: "iln_d4"
