dataset:
  name: Durlar
  type: range_images_durlar
  args:
    directory: /cluster/work/riner/users/biyang/iln/samples/
    high_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_new/train/depth/all/
    low_res_path: /cluster/work/riner/users/biyang/dataset/depth_intensity_new/train/depth/all/
    # res_in: '32_2048'
    # res_out: '128_2048'

model:
  name: lsr
  output: /cluster/work/riner/users/biyang/experiment/durlar/lsr/
  args:
    scale_h: 4
    scale_w: 1

logger:
  wandb_disabled: False
  # evaluation = False
  # save_pcd = False
  # project_name = "lidar_sr_network"
  project_name: 'sota_durlar'
  entity: "biyang"
  run_name: "lidar super resolution network"
  group_name: "LSR"