dataset:
  name: Carla
  type: range_images
  args:
    directory: ./dataset/Carla
    scene_ids:
      - Town01
      - Town02
      - Town03
      - Town04
      - Town05
      - Town06
    res_in: '16_1024'
    res_out: '64_1024'
    memory_fetch: false

model:
  name: lsr
  output: /cluster/work/riner/users/biyang/experiment/carla/lsr_16x1024_64x1024/
  args:
    scale_h: 4
    scale_w: 1



logger:
  wandb_disabled: False
  # evaluation = False
  # save_pcd = False
  # project_name = "lidar_sr_network"
  project_name: 'sota_carla'
  entity: "biyang"
  run_name: "lsr_16x1024_64x1024"
  group_name: "LSR"