dataset:
  name: Kitti
  type: range_images_kitti
  args:
    directory: /cluster/work/riner/users/biyang/iln/samples/
    high_res_path: /cluster/work/riner/users/biyang/dataset/KITTI/train20000
    low_res_path: /cluster/work/riner/users/biyang/dataset/KITTI/train20000
    res_in: '4_1024'
    res_out: '64_1024'

model:
  name: lsr
  output: /cluster/work/riner/users/biyang/experiment/carla/lsr_4x1024/
  args:
    scale_h: 16
    scale_w: 1

logger:
  wandb_disabled: False
  # evaluation = False
  # save_pcd = False
  # project_name = "lidar_sr_network"
  project_name: 'sota_kitti'
  entity: "biyang"
  run_name: "lsr_4x1024"
  group_name: "LSR"